# Generated by Django 3.2.7 on 2021-09-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210915_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpatient',
            name='assignDoctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.doctor'),
        ),
    ]
