# Generated by Django 3.2.7 on 2021-09-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210916_0951'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctor',
            table='doctor',
        ),
    ]
