# Generated by Django 3.2.7 on 2021-09-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_doctor_drid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctor',
            table=None,
        ),
    ]
